/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import Logic.Number;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author truon
 */
public class Main_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Main_Interface
     */
    DefaultListModel<String> model = new DefaultListModel<>();
    char asm;
    
    
    int AB;

    public Main_Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        A = new javax.swing.JLabel();
        B = new javax.swing.JLabel();
        textNumberOfB = new javax.swing.JTextField();
        textNumberOfA = new javax.swing.JTextField();
        notificationOfA = new javax.swing.JLabel();
        notificationOfB = new javax.swing.JLabel();
        resultOfCalculation = new javax.swing.JTextField();
        calculation = new javax.swing.JLabel();
        numberRemainder = new javax.swing.JTextField();
        remainderName = new javax.swing.JLabel();
        randomNumber = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        addition = new javax.swing.JButton();
        subtraction = new javax.swing.JButton();
        multiplication = new javax.swing.JButton();
        division = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnPerc = new javax.swing.JButton();
        btnDeci = new javax.swing.JButton();
        btnBackA = new javax.swing.JButton();
        btnBackB = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        calculationResults = new javax.swing.JLabel();
        remainderResults = new javax.swing.JLabel();
        NumberA = new javax.swing.JLabel();
        NumberB = new javax.swing.JLabel();
        textResultsCal = new javax.swing.JTextField();
        textRemainderCal = new javax.swing.JTextField();
        textTypeOfACal = new javax.swing.JTextField();
        textTypeOfBCal = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        calculationResults1 = new javax.swing.JLabel();
        remainderResults1 = new javax.swing.JLabel();
        NumberA1 = new javax.swing.JLabel();
        NumberB1 = new javax.swing.JLabel();
        textResults1 = new javax.swing.JTextField();
        textRemainder1 = new javax.swing.JTextField();
        textTypeOfA1 = new javax.swing.JTextField();
        textTypeOfB1 = new javax.swing.JTextField();
        copyResults = new javax.swing.JButton();
        CheckResults1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        OpenFile = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Tool = new javax.swing.JMenu();
        HStry = new javax.swing.JMenuItem();
        plugins = new javax.swing.JMenuItem();
        options = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Big Number Calculator");

        jPanel1.setBackground(new java.awt.Color(2, 41, 60));

        jPanel3.setBackground(new java.awt.Color(241, 243, 206));

        A.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        A.setText("Number A");

        B.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        B.setText("Number B");

        textNumberOfB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textNumberOfB.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumberOfB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNumberOfBMouseClicked(evt);
            }
        });

        textNumberOfA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textNumberOfA.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textNumberOfA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNumberOfAMouseClicked(evt);
            }
        });

        notificationOfA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        notificationOfA.setForeground(new java.awt.Color(255, 0, 0));

        notificationOfB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        notificationOfB.setForeground(new java.awt.Color(255, 0, 0));

        resultOfCalculation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        calculation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculation.setText("Result");

        numberRemainder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        remainderName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        randomNumber.setBackground(new java.awt.Color(0, 0, 0));
        randomNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        randomNumber.setForeground(new java.awt.Color(255, 255, 255));
        randomNumber.setText("Random Number");
        randomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomNumberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calculation, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(remainderName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resultOfCalculation)
                                    .addComponent(numberRemainder)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 114, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textNumberOfA, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNumberOfB, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B)
                                    .addComponent(A))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(notificationOfA, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(notificationOfB, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(randomNumber))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationOfA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumberOfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notificationOfB, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumberOfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultOfCalculation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculation))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remainderName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberRemainder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(randomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(241, 243, 206));

        addition.setBackground(new java.awt.Color(0, 0, 0));
        addition.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addition.setForeground(new java.awt.Color(255, 255, 255));
        addition.setText("+");
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });

        subtraction.setBackground(new java.awt.Color(0, 0, 0));
        subtraction.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        subtraction.setForeground(new java.awt.Color(255, 255, 255));
        subtraction.setText("-");
        subtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionActionPerformed(evt);
            }
        });

        multiplication.setBackground(new java.awt.Color(0, 0, 0));
        multiplication.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        multiplication.setForeground(new java.awt.Color(255, 255, 255));
        multiplication.setText("x");
        multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationActionPerformed(evt);
            }
        });

        division.setBackground(new java.awt.Color(0, 0, 0));
        division.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        division.setForeground(new java.awt.Color(255, 255, 255));
        division.setText("/");
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(0, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("AC");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnPerc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPerc.setText("%");
        btnPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPercActionPerformed(evt);
            }
        });

        btnDeci.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDeci.setText(",");
        btnDeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeciActionPerformed(evt);
            }
        });

        btnBackA.setBackground(new java.awt.Color(0, 0, 0));
        btnBackA.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnBackA.setForeground(new java.awt.Color(255, 255, 255));
        btnBackA.setText("A-");
        btnBackA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAActionPerformed(evt);
            }
        });

        btnBackB.setBackground(new java.awt.Color(0, 0, 0));
        btnBackB.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnBackB.setForeground(new java.awt.Color(255, 255, 255));
        btnBackB.setText("B-");
        btnBackB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBackA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBackB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeci, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jPanel5.setBackground(new java.awt.Color(241, 243, 206));

        calculationResults.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculationResults.setText("Result");

        remainderResults.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        remainderResults.setText("Remainder");

        NumberA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NumberA.setText("Number A");

        NumberB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NumberB.setText("Number B");

        textResultsCal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textResultsCal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textRemainderCal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textRemainderCal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textTypeOfACal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTypeOfACal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textTypeOfBCal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTypeOfBCal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculationResults, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberB)
                    .addComponent(NumberA)
                    .addComponent(remainderResults))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textTypeOfACal, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(textRemainderCal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textResultsCal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textTypeOfBCal))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculationResults)
                            .addComponent(textResultsCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(remainderResults, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textRemainderCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeOfACal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeOfBCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberB))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(241, 243, 206));

        calculationResults1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculationResults1.setText("Result");

        remainderResults1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        remainderResults1.setText("Remainder");

        NumberA1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NumberA1.setText("Number A");

        NumberB1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NumberB1.setText("Number B");

        textResults1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textResults1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textRemainder1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textRemainder1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textTypeOfA1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTypeOfA1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        textTypeOfB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textTypeOfB1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        copyResults.setBackground(new java.awt.Color(0, 0, 0));
        copyResults.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        copyResults.setForeground(new java.awt.Color(255, 255, 255));
        copyResults.setText("Copy the results");
        copyResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calculationResults1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberB1)
                            .addComponent(NumberA1)
                            .addComponent(remainderResults1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTypeOfA1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(textRemainder1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textResults1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textTypeOfB1)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(copyResults)
                        .addGap(0, 294, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(copyResults, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculationResults1)
                            .addComponent(textResults1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(remainderResults1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textRemainder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeOfA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberA1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTypeOfB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberB1))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        CheckResults1.setFont(new java.awt.Font("SimSun-ExtB", 3, 36)); // NOI18N
        CheckResults1.setForeground(new java.awt.Color(0, 153, 153));
        CheckResults1.setText("COMPARE RESULTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CheckResults1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CheckResults1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        File.setText("File");

        OpenFile.setText("Open");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        File.add(OpenFile);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        File.add(save);

        Delete.setText("Delete");
        File.add(Delete);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar2.add(File);

        Tool.setText("Tool");

        HStry.setText("History");
        HStry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HStryActionPerformed(evt);
            }
        });
        Tool.add(HStry);

        plugins.setText("Plugins");
        Tool.add(plugins);

        options.setText("Options");
        Tool.add(options);

        about.setText("About");
        Tool.add(about);

        jMenuBar2.add(Tool);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        // TODO add your handling code here:
        asm = '+';
        numberRemainder.setText("");
        remainderName.setText("");
        String textA = textNumberOfA.getText();
        String textB = textNumberOfB.getText();
        boolean Aempty = false;
        boolean Bempty = false;
        if ("".equals(textNumberOfA.getText())) {
            Aempty = true;
            textA = "1";
        }
        if ("".equals(textNumberOfB.getText())) {
            Bempty = true;
            textB = "1";
        }
        Number numberA = new Number(textA);
        Number numberB = new Number(textB);
        if (Aempty) {
            notificationOfA.setText("Please provide value A!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberA.isIntegerList()) {
                notificationOfA.setText("Please provide a valid A value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfA.setText("");
            }
        }
        if (Bempty) {
            notificationOfB.setText("Please provide value B!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberB.isIntegerList()) {
                notificationOfB.setText("Please provide a valid B value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfB.setText("");
            }
        }

        if (!Aempty && !Bempty) {
            if (numberA.isIntegerList() && numberB.isIntegerList()) {
                Number numberResult = new Number();
                numberResult = Number.addition(numberA, numberB);
                resultOfCalculation.setText(numberResult.numberToString());
                calculation.setText("A + B =");
                textTypeOfACal.setText(textA);
                textTypeOfBCal.setText(textB);
                textResultsCal.setText(numberResult.numberToString());
                textRemainderCal.setText("");
                
                model.add(0, "  ");
                model.add(0, "Result A + B = " + numberResult.numberToString());
                model.add(0, "Number B = " + textB);
                model.add(0, "Number A = " + textA);
                model.add(0, "==== The following calculation results ====");
            }
        } else {
            resultOfCalculation.setText("");
        }

    }//GEN-LAST:event_additionActionPerformed

    private void subtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionActionPerformed
        // TODO add your handling code here:
        asm = '-';
        numberRemainder.setText("");
        remainderName.setText("");
        String textA = textNumberOfA.getText();
        String textB = textNumberOfB.getText();
        boolean Aempty = false;
        boolean Bempty = false;
        if ("".equals(textNumberOfA.getText())) {
            Aempty = true;
            textA = "1";
        }
        if ("".equals(textNumberOfB.getText())) {
            Bempty = true;
            textB = "1";
        }
        Number numberA = new Number(textA);
        Number numberB = new Number(textB);
        if (Aempty) {
            notificationOfA.setText("Please provide value A!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberA.isIntegerList()) {
                notificationOfA.setText("Please provide a valid A value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfA.setText("");
            }
        }
        if (Bempty) {
            notificationOfB.setText("Please provide value B!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberB.isIntegerList()) {
                notificationOfB.setText("Please provide a valid B value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfB.setText("");
            }
        }

        if (!Aempty && !Bempty) {
            if (numberA.isIntegerList() && numberB.isIntegerList()) {
                Number numberResult = new Number();
                numberResult = Number.subtraction(numberA, numberB);
                resultOfCalculation.setText(numberResult.numberToString());
                calculation.setText("A - B =");
                textTypeOfACal.setText(textA);
                textTypeOfBCal.setText(textB);
                textResultsCal.setText(numberResult.numberToString());
                textRemainderCal.setText("");
                
                model.add(0, "  ");
                model.add(0, "Result A - B = " + numberResult.numberToString());
                model.add(0, "Number B = " + textB);
                model.add(0, "Number A = " + textA);
                model.add(0, "==== The following calculation results ====");
            } else {
                resultOfCalculation.setText("");
                calculation.setText("Result");
            }
        } else {
            resultOfCalculation.setText("");
            calculation.setText("Result");
        }
    }//GEN-LAST:event_subtractionActionPerformed

    private void multiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationActionPerformed
        // TODO add your handling code here:   
        asm = '*';
        numberRemainder.setText("");
        remainderName.setText("");
        String textA = textNumberOfA.getText();
        String textB = textNumberOfB.getText();
        boolean Aempty = false;
        boolean Bempty = false;
        if ("".equals(textNumberOfA.getText())) {
            Aempty = true;
            textA = "1";
        }
        if ("".equals(textNumberOfB.getText())) {
            Bempty = true;
            textB = "1";
        }
        Number numberA = new Number(textA);
        Number numberB = new Number(textB);
        if (Aempty) {
            notificationOfA.setText("Please provide value A!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberA.isIntegerList()) {
                notificationOfA.setText("Please provide a valid A value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfA.setText("");
            }
        }
        if (Bempty) {
            notificationOfB.setText("Please provide value B!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
        } else {
            if (!numberB.isIntegerList()) {
                notificationOfB.setText("Please provide a valid B value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
            } else {
                notificationOfB.setText("");
            }
        }
        if (!Aempty && !Bempty) {
            if (numberA.isIntegerList() && numberB.isIntegerList()) {
                Number numberResult = new Number();
                numberResult = Number.multiplication(numberA, numberB);
                resultOfCalculation.setText(numberResult.numberToString());
                calculation.setText("A x B =");
                textTypeOfACal.setText(textA);
                textTypeOfBCal.setText(textB);
                textResultsCal.setText(numberResult.numberToString());
                textRemainderCal.setText("");
                
                model.add(0, "  ");
                model.add(0, "Result A x B = " + numberResult.numberToString());
                model.add(0, "Number B = " + textB);
                model.add(0, "Number A = " + textA);
                model.add(0, "==== The following calculation results ====");
            } else {
                resultOfCalculation.setText("");
                calculation.setText("Result");
            }
        } else {
            resultOfCalculation.setText("");
            calculation.setText("Result");
        }
    }//GEN-LAST:event_multiplicationActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
        asm = '/';
        String textA = textNumberOfA.getText();
        String textB = textNumberOfB.getText();
        boolean Aempty = false;
        boolean Bempty = false;
        if ("".equals(textNumberOfA.getText())) {
            Aempty = true;
            textA = "1";
        }
        if ("".equals(textNumberOfB.getText())) {
            Bempty = true;
            textB = "1";
        }
        Number numberA = new Number(textA);
        Number numberB = new Number(textB);
        if (Aempty) {
            notificationOfA.setText("Please provide value A!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
            numberRemainder.setText("");
            remainderName.setText("");
        } else {
            if (!numberA.isIntegerList()) {
                notificationOfA.setText("Please provide a valid A value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
                numberRemainder.setText("");
                remainderName.setText("");
            } else {
                notificationOfA.setText("");
                numberRemainder.setText("");
                remainderName.setText("");
            }
        }
        if (Bempty) {
            notificationOfB.setText("Please provide value B!");
            resultOfCalculation.setText("");
            calculation.setText("Result");
            numberRemainder.setText("");
            remainderName.setText("");
        } else {
            if (!numberB.isIntegerList()) {
                notificationOfB.setText("Please provide a valid B value!");
                resultOfCalculation.setText("");
                calculation.setText("Result");
                numberRemainder.setText("");
                remainderName.setText("");
            } else {
                notificationOfB.setText("");
                numberRemainder.setText("");
                remainderName.setText("");
            }
        }
        if (Number.checkZero(numberB)) {
            notificationOfB.setText("B value CANNOT be 0 !");
        }
        if (!Aempty && !Bempty && !Number.checkZero(numberB)) {
            if (numberA.isIntegerList() && numberB.isIntegerList()) {
                Number numberResult = new Number();
                Number numberAA = new Number(numberA);
                Number numberBB = new Number(numberB);
                numberResult = Number.division(numberA, numberB);
                numberRemainder.setText(Number.remainderNumber(numberResult, numberAA, numberBB).numberToString());
                resultOfCalculation.setText(numberResult.numberToString());
                calculation.setText("A / B =");
                remainderName.setText("Remainder");
                textTypeOfACal.setText(textA);
                textTypeOfBCal.setText(textB);
                textResultsCal.setText(numberResult.numberToString());
                String re = numberRemainder.getText();
                textRemainderCal.setText(re);
                
                model.add(0, "  ");
                model.add(0, "NumberRemainder = " + re);
                model.add(0, "Result A / B = " + numberResult.numberToString());
                model.add(0, "Number B = " + textB);
                model.add(0, "Number A = " + textA);
                model.add(0, "==== The following calculation results ====");
                
            } else {
                resultOfCalculation.setText("");
                calculation.setText("Result");
                numberRemainder.setText("");
                remainderName.setText("");
            }
        } else {
            resultOfCalculation.setText("");
            calculation.setText("Result");
            numberRemainder.setText("");
            remainderName.setText("");
        }
    }//GEN-LAST:event_divisionActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        textNumberOfA.setText("");
        textNumberOfB.setText("");
        resultOfCalculation.setText("");
        numberRemainder.setText("");
        
        textResultsCal.setText("");
        textRemainderCal.setText("");
        textTypeOfACal.setText("");
        textTypeOfBCal.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAActionPerformed
        // TODO add your handling code here:
        // Xóa một ký tự cuối cùng của text field
        String textA = textNumberOfA.getText();
        if (textA.length() > 0) {
            textA = textA.substring(0, textA.length() - 1);
        }
        textNumberOfA.setText(textA);
    }//GEN-LAST:event_btnBackAActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 7 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "7");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "7");
        }

    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 8 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "8");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "8");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 9 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "9");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "9");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 4 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "4");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "4");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 5 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "5");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "5");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 6 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "6");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "6");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 1 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "1");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "1");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 2 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "2");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "2");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 3 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "3");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "3");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự 0 vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "0");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "0");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự % vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + "%");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + "%");
        }
    }//GEN-LAST:event_btnPercActionPerformed

    private void btnDeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeciActionPerformed
        // TODO add your handling code here:
        // Thêm ký tự , vào text field
        if (AB == 1) {
            textNumberOfA.setText(textNumberOfA.getText() + ",");
        }
        if (AB == 2) {
            textNumberOfB.setText(textNumberOfB.getText() + ",");
        }
    }//GEN-LAST:event_btnDeciActionPerformed

    private void btnBackBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackBActionPerformed
        // TODO add your handling code here:
        String textB = textNumberOfB.getText();
        if (textB.length() > 0) {
            textB = textB.substring(0, textB.length() - 1);
        }
        textNumberOfB.setText(textB);
    }//GEN-LAST:event_btnBackBActionPerformed

    private void textNumberOfAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNumberOfAMouseClicked
        // TODO add your handling code here:
        // click vào khung A để nhập
        AB = 1;
    }//GEN-LAST:event_textNumberOfAMouseClicked

    private void textNumberOfBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNumberOfBMouseClicked
        // TODO add your handling code here:
        // click vào khung B để nhập
        AB = 2;
    }//GEN-LAST:event_textNumberOfBMouseClicked

    private void randomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomNumberActionPerformed

        Random random = new Random();
        int n = random.nextInt(20);
        // Generate non-empty number for Number A
        String a = "";
        int q;
        do {
            q = random.nextInt(10);
            a += String.valueOf(q);
        } while (q == 0);
        for (int i = 1; i < n; i++) {
            q = random.nextInt(10);
            a += String.valueOf(q);
        }
        textNumberOfA.setText(a);

        n = random.nextInt(20);
        // Generate non-empty number for Number B
        a = "";
        do {
            q = random.nextInt(10);
            a += String.valueOf(q);
        } while (q == 0);
        for (int i = 1; i < n; i++) {
            q = random.nextInt(10);
            a += String.valueOf(q);
        }
        textNumberOfB.setText(a);
    }//GEN-LAST:event_randomNumberActionPerformed

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter txt = new FileNameExtensionFilter("Text files (.txt)", "txt");
        fileChooser.setFileFilter(txt);
        fileChooser.setMultiSelectionEnabled(false);
        File file = null;
        String num1 = "";
        String num2 = "";

        int x = fileChooser.showOpenDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                // Read the first line and extract only numbers
                String line = br.readLine();
                num1 = line.replaceAll("[^0-9]", "");

                // Read the second line and extract only numbers
                line = br.readLine();
                num2 = line.replaceAll("[^0-9]", "");
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        // Display the extracted numbers
        textNumberOfA.setText(num1);
        textNumberOfB.setText(num2);
    }//GEN-LAST:event_OpenFileActionPerformed

    private void HStryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HStryActionPerformed

        new history(model).setVisible(true);
        
    }//GEN-LAST:event_HStryActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter txt = new FileNameExtensionFilter("Text files (.txt)", "txt");
        fileChooser.setFileFilter(txt);
        fileChooser.setMultiSelectionEnabled(false);

        int x = fileChooser.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
        File file = fileChooser.getSelectedFile();

        if(asm == '+'){
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file + ".txt"))) {

            String num1Str = textNumberOfA.getText();
            String num2Str = textNumberOfB.getText();
            String num3Str = resultOfCalculation.getText();

            bw.write("Number A = " + num1Str);
            bw.newLine();
            bw.write("Number B = " + num2Str);
            bw.newLine();
            bw.write("Results A + B = " + num3Str);
        } catch (IOException e) {
        }
        }
        if(asm == '-'){
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file + ".txt"))) {

            String num1Str = textNumberOfA.getText();
            String num2Str = textNumberOfB.getText();
            String num3Str = resultOfCalculation.getText();

            bw.write("Number A = " + num1Str);
            bw.newLine();
            bw.write("Number B = " + num2Str);
            bw.newLine();
            bw.write("Results A - B = " + num3Str);
        } catch (IOException e) {
        }
        }
        if(asm == '*'){
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file + ".txt"))) {

            String num1Str = textNumberOfA.getText();
            String num2Str = textNumberOfB.getText();
            String num3Str = resultOfCalculation.getText();

            bw.write("Number A = " + num1Str);
            bw.newLine();
            bw.write("Number B = " + num2Str);
            bw.newLine();
            bw.write("Results A x B = " + num3Str);
        } catch (IOException e) {
        }
        }
        if(asm == '/'){
            try (BufferedWriter bw = new BufferedWriter(new FileWriter(file + ".txt"))) {

            String num1Str = textNumberOfA.getText();
            String num2Str = textNumberOfB.getText();
            String num3Str = resultOfCalculation.getText();
            String num4Str = numberRemainder.getText();

            bw.write("Number A = " + num1Str);
            bw.newLine();
            bw.write("Number B = " + num2Str);
            bw.newLine();
            bw.write("Results A / B = " + num3Str);
            bw.newLine();
            bw.write("numberRemainder = " + num4Str);
        } catch (IOException e) {
        }
        }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void copyResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyResultsActionPerformed
        // TODO add your handling code here:
        //copy data từ kết quả ô trên
        textResults1.setText(textResultsCal.getText());
        textRemainder1.setText(textRemainderCal.getText());
        textTypeOfA1.setText(textTypeOfACal.getText());
        textTypeOfB1.setText(textTypeOfBCal.getText());
    }//GEN-LAST:event_copyResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main_Interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel B;
    private javax.swing.JLabel CheckResults1;
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem HStry;
    private javax.swing.JLabel NumberA;
    private javax.swing.JLabel NumberA1;
    private javax.swing.JLabel NumberB;
    private javax.swing.JLabel NumberB1;
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JMenu Tool;
    private javax.swing.JMenuItem about;
    private javax.swing.JButton addition;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBackA;
    private javax.swing.JButton btnBackB;
    private javax.swing.JButton btnDeci;
    private javax.swing.JButton btnPerc;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel calculation;
    private javax.swing.JLabel calculationResults;
    private javax.swing.JLabel calculationResults1;
    private javax.swing.JButton copyResults;
    private javax.swing.JButton division;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton multiplication;
    private javax.swing.JLabel notificationOfA;
    private javax.swing.JLabel notificationOfB;
    private javax.swing.JTextField numberRemainder;
    private javax.swing.JMenuItem options;
    private javax.swing.JMenuItem plugins;
    private javax.swing.JButton randomNumber;
    private javax.swing.JLabel remainderName;
    private javax.swing.JLabel remainderResults;
    private javax.swing.JLabel remainderResults1;
    private javax.swing.JTextField resultOfCalculation;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton subtraction;
    private javax.swing.JTextField textNumberOfA;
    private javax.swing.JTextField textNumberOfB;
    private javax.swing.JTextField textRemainder1;
    private javax.swing.JTextField textRemainderCal;
    private javax.swing.JTextField textResults1;
    private javax.swing.JTextField textResultsCal;
    private javax.swing.JTextField textTypeOfA1;
    private javax.swing.JTextField textTypeOfACal;
    private javax.swing.JTextField textTypeOfB1;
    private javax.swing.JTextField textTypeOfBCal;
    // End of variables declaration//GEN-END:variables

}
